apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: postgres-exporter-servicemonitor
  namespace: monitoring
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: prometheus-postgres-exporter
  endpoints:
    - port: metrics
      path: /metrics
      interval: 30s

