apiVersion: v1
kind: Service
metadata:
  name: postgres-exporter-prometheus-postgres-exporter
  namespace: monitoring
  labels:
    app: prometheus-postgres-exporter
    release: postgres-exporter
spec:
  selector:
    app: prometheus-postgres-exporter
    release: postgres-exporter
  ports:
    - name: metrics
      port: 9187
      targetPort: 9187
      protocol: TCP
  type: ClusterIP

