apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-my-postgres-postgresql-0
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: standard  

