apiVersion: v1
kind: Pod
metadata:
  name: temp-postgres-pod
  namespace: default
spec:
  containers:
  - name: temp-postgres-container
    image: ubuntu:latest
    command:
      - "sleep"
      - "3600"
    resources:
      requests:
        memory: "128Mi"
        cpu: "100m"
      limits:
        memory: "256Mi"
        cpu: "500m"

